version: 2
jobs:
   build:
     docker:
       - image: circleci/python:2.7
       - image: circleci/python:3.5
     steps:
       - checkout
       - run: sudo apt-get install python-tox
       - run: tox
