version: 2
jobs:
  build:
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/python:3.5
    steps:
    # Set things up
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    #- run: pyenv global 2.7.12 3.5.3
    - run: pip install --user tox

    # Run tests
    - run: PATH=$HOME/.local/bin/:$PATH tox
    - run: PATH=$HOME/.local/bin/:$PATH tox --version
    - run: mkdir -p $CIRCLE_TEST_REPORTS/reports/ && mv TEST-*.xml $CIRCLE_TEST_REPORTS/reports/

    # Store outputs
    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
